export default {
  user_login: 'auth/login',
  forgot_password_otp: 'user-management/forgot-user-admin-password',
  forgot_password_otp_verification:
    '/user-management/forgot-user-admin-password',
  forgot_password_set_new_password:
    '/user-management/forgot-user-admin-password',
  delete_trainee_registration: '/lms/delete-trainee-registration',
  common_get_list: 'common/get-list',
  common_file_upload: 'common/file-upload',

  //Vehicle Management
  list_vehicle_details: 'vehicle-management/list-vehicle-details',
  update_vehicle_details: 'vehicle-management/update-vehicle-details',
  add_vehicle_details: 'vehicle-management/add-vehicle-details',
  delete_vehicle_details: 'vehicle-management/delete-vehicle-details',
  list_assigned_details: 'vehicle-management/list-assigned-vehicle',
  removed_assigned_details: 'vehicle-management/remove-assigned-vehicle',
  assign_new_driver: 'vehicle-management/assign-new-driver',
  list_assign_vehicle_driver:
    'vehicle-management/list-assigned-vehicle-history',
  delete_assign_vehicle: 'vehicle-management/delete-assigned-vehicle',
  add_assign_vehicle: 'vehicle-management/assign-vehicle',
  update_assign_vehicle: 'vehicle-management/update-assigned-vehicle',
  list_trip_details: 'vehicle-management/list-trip-details',
  add_trip_details: 'vehicle-management/add-trip-details',
  update_trip_details: 'vehicle-management/update-trip-details',
  delete_trip_details: 'vehicle-management/delete-trip-details',

  //Hostel Management
  guest_list: 'lms/list-guest-registration',
  delete_guest: 'lms/delete-guest-registration',
  add_guest: 'lms/add-guest-registration',
  update_guest: 'lms/update-guest-registration',
  hostel_details: 'hostel/list-hostel-details',
  update_hostel_details: 'hostel/update-hostel-details',
  delete_hostel_details: 'hostel/delete-hostel-details',
  add_hostel_details: 'hostel/add-hostel-details',
  hostel_floor_details: 'hostel/list-hostel-floor-details',
  delete_hostel_floor: 'hostel/delete-hostel-floor-details',
  add_hostel_floor: 'hostel/add-hostel-floor-details',
  update_hostel_floor: 'hostel/update-hostel-floor-details',
  hostel_room_details: 'hostel/list-hostel-room-details',
  update_hostel_room: 'hostel/update-hostel-room-details',
  delete_hostel_room: 'hostel/delete-hostel-room-details',
  add_hostel_room: 'hostel/add-hostel-room-details',
  bed_details_room: 'hostel/list-hostel-bed-details',
  update_bed_details_room: 'hostel/update-hostel-bed-details',
  delete_bed_details_room: 'hostel/delete-hostel-bed-details',
  add_bed_details_room: 'hostel/add-hostel-bed-details',
  hostel_allocation_details: 'hostel/list-hostel-allocation-details',
  hostel_allocation_delete: 'hostel/delete-hostel-allocation-details',
  hostel_release: 'hostel/release-hostel-by-training-id',
  hostel_allocation: 'hostel/add-hostel-allocation-by-admin',
  update_hostel_allocation: 'hostel/update-hostel-allocation-details',

  //Dashboard
  vendor_dashboard: 'vendor/vendor-dashboard',
  list_vendor: 'vendor/list-vendor',
  hostel_planning_data: 'dashboard/list-hostel-planning-data',
  hostel_report_data: 'dashboard/list-hostel-wise-allocated-count',
  hostel_data: 'dashboard/dashboard-data',
  hostel_room_details_dashboard: 'dashboard/room-details',
  hostel_bed_details_dashboard: 'dashboard/bed-details',
  dashboard_block_bed_list: 'dashboard/list-blocked-bed',
  dashboard_unblock_bed_list: 'dashboard/unblock-bed',
  dashboard_block_bed: 'dashboard/block-bed',

  //LMS
  list_training_category: 'lms/list-training-category',
  add_training_category: 'lms/add-training-category',
  update_training_category: 'lms/update-training-category',
  download_training_category: 'lms/download-training-category',
  list_training_details: 'lms/list-training-details',
  add_fileNo_training_details: 'lms/add-file-number-to-training-details',
  update_trainee_login_details: 'lms/update-trainee-login',
  extend_training_end_date: 'lms/extend-training-end-date',
  delete_training_details: 'lms/delete-training-details',
  add_training_details: 'lms/add-training-details',
  update_training_details: 'lms/update-training-details',
  list_training_batch_details: 'lms/list-training-batch-details',
  update_training_batch_details: 'lms/update-training-batch-details',
  list_trainee_details: 'lms/list-trainee-details',
  merge_training_batch_details: 'lms/merge-training-batch-details',
  list_trainee_registration: 'lms/list-trainee-registration',
  add_trainee_registration_bulk: 'lms/add-trainee-registration-in-bulk',
  add_trainee_registration: 'lms/add-trainee-registration',
  update_trainee_registration: 'lms/update-trainee-registration',
  approve_training_id_card: 'lms/approve-training-id-card',
  download_training_id_card: 'lms/download-training-id-card',
  download_trainee_reg_form: 'lms/download-trainee-registration-form',
  download_trainee_details: 'lms/download-trainee-details',
  list_trainee_manage_indemnity_bond:
    'lms/list-trainee-management-indemnity-bond',
  download_trainee_manage_indemnity_bond:
    '/lms/download-trainee-indemnity-bond',
  release_trainee_from_training: 'lms/release-trainee-from-training',
  add_mukhiya_registration: 'lms/add-mukhiya-registration',
  list_faculty_details: 'lms/list-faculty-details',
  update_faculty_details: 'lms/update-faculty-details',
  list_faculty_confirmation: 'lms/list-faculty-confirmation',
  update_faculty_confirmation: 'lms/update-faculty-confirmation',
  report_list_faculty_feedback_report: 'report/list-faculty-feedback-report',
  report_list_faculty_sub_feedback_report:
    'report/list-faculty-subject-feedback-report',
  report_list_faculty_tpoic_feedback_report:
    'report/list-faculty-topic-feedback-report',
  report_list_feedback_trainne_details:
    'report/list-faculty-feedback-report-trainee-details',
  delete_faculty_details: '/lms/delete-faculty-details',
  list_knowledge_managemnet: 'lms/list-knowledge-management-subject',
  list_knowledge_managemnet_sub_topic:
    '/lms/list-knowledge-management-subject-topic',
  list_class_location_details: 'lms/list-class-location-details',
  update_class_location_details: 'lms/update-class-location-details',
  list_class_sub_location_details: 'lms/list-class-sub-locations-details',
  update_class_sub_location_details: 'lms/update-class-sub-locations-details',
  list_classroom_time_table_manage: 'lms/list-classroom-management-time-table',
  list_assignment_question_bank: 'lms/list-assignment-question-bank',
  list_assessment_assignment_assign_que:
    'lms/list-assessment-assignment-assign-question',
  list_assessment_assignment: 'lms/list-assessment-assignment',
  update_assessment_assignment: 'lms/update-assessment-assignment',
  list_assignment_response_report: 'lms/list-assignment-response-report',
  list_assignment_response: 'lms/list-assignment-response',
  list_assessment_create_test: 'lms/list-assessment-create-test',
  update_assessment_create_test: 'lms/update-assessment-create-test',
  list_assessment_test_assign_question:
    'lms/list-assessment-test-assign-question',
  exam_question_order_randomization: 'lms/exam-question-order-randomization',
  list_assessment_question_bank: 'lms/list-assessment-question-bank',
  list_examination_submission_test_list:
    'lms/list-examination-submission-test-list',
  list_examination_submission_report: 'lms/list-examination-submission-report',
  list_examination_submission_answer: 'lms/list-examination-submission-answer',

  //PHC
  list_patient_prescriptions: 'phc/list-patient-prescriptions',
  list_medicine: 'phc/list-medicine',
  list_medicine_type: 'phc/list-medicine-type',
  list_medicine_batch: 'phc/list-medicine-batch',
  list_pharmacy_report: 'phc/pharmacy-report',
  list_trainee_bmi: 'phc/list-trainee-bmi',
  list_patient_symptoms_details: 'phc/list-patient-symptoms-details',

  //Invoice and Bill Management
  list_vendor_request_movemnet: 'vendor/list-vendor-request-movement',
  assignee_list_vendor: 'vendor/select-assignee-to-vendor-request',
  assignee_add_vendor: 'vendor/add-assignee-to-vendor-request',
  list_vendor_payment_history: 'vendor/list-vendor-payment-history',
  add_vendor_payment_history: 'vendor/add-vendor-payment-history',
  update_vendor_payment_history: 'vendor/update-vendor-payment-history',

  //User Management
  list_internal_user: 'user-management/list-internal-users',
  approve_internal_user_status: 'user-management/approve-internal-users-status',
  delete_internal_user: 'user-management/delete-internal-users',
  list_admin_role: 'user-management/list-admin-role',
  add_admin_role: 'user-management/add-admin-role',
  update_admin_role: 'user-management/update-admin-role',
  delete_admin_role: 'user-management/delete-admin-role',
  list_permissions_name: 'user-management/list-permissions-name',
  list_global_permissions_list: 'user-management/list-global-admin-permissions',
  update_global_permissions_list:
    'user-management/update-global-admin-permissions',
  add_user_management: 'user-management/add-internal-users',
  update_user_management: 'user-management/update-internal-users',

  //Support
  list_support_raise_complain: 'support/list-support-raise-complain',
  delete_support_raise_complain: 'support/delete-support-raise-complain',
  resolve_support_raise_complain: 'support/resolve-support-raised-complain',

  //Feedback Management
  list_feedback_category: 'feedback/list-feedback-category',
  update_feedback_category: 'feedback/update-feedback-category',
  delete_feedback_category: 'feedback/delete-feedback-category',
  add_feedback_category: 'feedback/add-feedback-category',
  list_feedback_topic: 'feedback/list-feedback-topic',
  add_feedback_topic: 'feedback/add-feedback-topic',
  update_feedback_topic: 'feedback/update-feedback-topic',
  delete_feedback_topic: 'feedback/delete-feedback-topic',
  list_overallS_training_feedback: 'feedback/list-overall-training-feedback',
  list_faculty_feedback: 'feedback/list-faculty-feedback',
  delete_faculty_feedback: 'feedback/delete-faculty-feedback',
  list_feedback_response: 'feedback/list-feedback-response',
  delete_feedback_response: 'feedback/delete-feedback-response',
  list_training_wise_faculty:
    'report/list-training-wise-faculty-feedback-report',
  list_training_wise_faculty_count:
    'report/list-training-wise-faculty-class-count',
  list_training_wise_feedback_count:
    'report/list-training-wise-faculty-feedback-count',

  //Communication Management System
  communication_list_application: 'communication/list-application',
  communication_update_application: 'communication/update-application',
};
