export default {
  DropDownModal: 'DropDownModal',
  AlertOrganism: 'AlertOrganism',
  Login: 'Login',
  ForgotPassword: 'ForgotPassword',
  Dashboard: 'Dashboard',
  Profile: 'Profile',
  Menu: 'Menu',
  VehicleManagement: 'VehicleManagement',
  VehicleRegistration: 'VehicleRegistration',
  AddVehicle: 'AddVehicle',
  AssignVehicle: 'AssignVehicle',
  DriverMovementHistory: 'DriverMovementHistory',
  AddAssignVehicle: 'AddAssignVehicle',
};
