export default {
  DropDownModal: 'DropDownModal',
  AlertOrganism: 'AlertOrganism',
  Login: 'Login',
  ForgotPassword: 'ForgotPassword',
  Dashboard: 'Dashboard',
  Profile: 'Profile',
  Menu: 'Menu',
  VehicleManagement: 'VehicleManagement',
  VehicleRegistration: 'VehicleRegistration',
  AddVehicle: 'AddVehicle',
  AssignVehicle: 'AssignVehicle',
  DriverMovementHistory: 'DriverMovementHistory',
  AddAssignVehicle: 'AddAssignVehicle',
  CreateTour: 'CreateTour',
  CreateTourDetails: 'CreateTourDetails',
  AddCreateTour: 'AddCreateTour',
  HostelManagement: 'HostelManagement',
  Guest: 'Guest',
  AddGuest: 'AddGuest',
  Hostel: 'Hostel',
  HostelDetails: 'HostelDetails',
  AddHostelDetails: 'AddHostelDetails',
  FloorDetails: 'FloorDetails',
  AddFloorDetails: 'AddFloorDetails',
};
