export default {
  app_name: 'BIPARD',
  select: 'Select',
  search: 'Search',
  noDataFound: 'No Data Found',
  done: 'Done',
  ok: 'Ok',
  cancel: 'Cancel',
  yes: 'Yes',
  no: 'No',
  noInternet: 'No Internet',
  noInternetMessage:
    'No internet connection was found. Please check your connection or try again',
  tryAgain: 'Try again',
  remember_me: 'Remember me',
  bipard: 'Bihar Institute of Public Administration & Rural Development',
  welcome_to_bipard_erp: 'Welcome to BICTA!',
  sign_in: 'Sign In',
  message_1:
    "Training is a process by which officials' abilities are increased to perform specific tasks. Inspired by the changing global norms as per the social demands, training is an opportunity to move forward on the path of progress and deal with the challenges faced by society, which lacks negativity and is full of positivity. Through training, government talents are integrated into the mainstream of the nation's development by ensuring the necessary security and rights of citizens with transparency. It should be the duty of every public servant to try to incorporate the processes of discipline in his life and use them responsibly in public life - the inclusion of this process in training is necessary.",
  message_2:
    'Training of officials and employees does not only mean giving information about the requirements and techniques coming into their work area. Although all these dimensions are important parts and components of training, training is an essential process of developing the complete personality of the trainees. It is a verified fact that the process of selection of administrative officers is long and difficult and the people who are successfully selected in this selection process have special talent and knowledge of the subject. Therefore, in addition to the education related to the work techniques of the officials in the training institute, the focus should be on the overall development of their personality. To give a real shape to this principle, in addition to regular academic training, the trainees in Bipard are given physical education and yoga education, sports, etc.',
  message_3:
    'Special attention is given. Besides, arrangements are also made for India darshan, trekking and mountaineering, adventure travel etc. to enhance the knowledge of the officials. Team spirit and leadership skills are developed through these external and extracurricular activities.',
  message_4:
    "The publication of the magazine 'Unnayan', which embodies the monthly presentation of this institute, has fully contributed to its development. All the officers and other employees involved in this are making full use of their will and are witnessing its progress. The writings of various scholars on various subjects have made it mature.",
  message_5:
    'In the last year, BIPARD has created a unique identity for itself due to new applications related to training and innovations in administrative training. Bihar Government implements training with new consciousness through experiments based on new research to meet the demand of its various departments as per the requirement. BIPARD is showing a unique example of success by delivering quality training to many training programs despite short notice.',
  message_6:
    "Apart from training on administration and departmental subjects, the subject that is most needed in training modules today is discipline. Administrative discipline is not only indispensable in the achievement of organizational objectives but is also essential in personal life. In times of erosion of discipline, transplantation, promotion, and establishment of discipline have become the main objective and subject of BIPARD training, this training is proving to be universal. Without discipline all qualities become useless. To prove the proverb 'Multiple dishes without salt, BIPARD starts practicing physical exercises and yoga at 5.30 in the morning to inculcate discipline among the trainees. The fatigue and stress of continuous study throughout the day go away in the evening yoga practice. This creates awareness about discipline among the trainees and develops a feeling of cooperation, tolerance, participation, and adjustment. After accepting the bondage of discipline, they find it easier to execute administrative work with commitment and dedication. Administrative discipline holds its special place in the execution of time-bound tasks like law and order, disaster management, elections, etc. because these tasks require a specific work system instead of a general work system. This nature and diversity of training differentiates BIPARD trainees from other trainees. The trainees, after receiving training here, become completely disciplined and dedicate themselves to public service in the spirit of public welfare, that is why BIPARD focus is especially on discipline.",
  message_7:
    "Education is the backbone of the country's development. With the right direction of education, proper use of technologies becomes possible and new technologies are developed. It is well known that teachers are the builders of the nation. To implement this, this development yagya has been started by training the administrative officers and employees as well as teachers through BIPARD. The officers, employees and other people involved in raising BIPARD to great heights with their multifaceted service deserve congratulations. 'Unnayan' is succeeding in its objective by communicating this. Best wishes for its presentation.",
  dg_message: 'DG Message',
  dg_name: 'Dr. B. Rajender (IAS)',
  dg_designation: 'Director General, BIPARD',
  read_more: '...Read More',
  event_calendar: 'Event Calendar',
  this_month_event: 'This Month Event',
  notice: 'Notice',
  new_notice_found: 'New Notice(s) Found',
  no_new_notice_found: 'No New Notice Found',
  no_record_found: 'No record found',
  close: 'Close',
  username: 'Username',
  password: 'Password',
  role_required: 'Role is required',
  username_required: 'Username is required',
  password_required: 'Password is required',
  sign_in_button: 'Sign In',
  download_manual: 'Download User Manual for TRAINEE',
  forgot_password: 'Forgot Password?',
  copyright: '© 2025 BIPARD',
  designed_by: 'Designed and Developed By',
  codebucket: 'Codebucket Solutions Private Limited',
  forgot_password_title: 'Forgot Password',
  otp: 'OTP',
  otp_required: 'OTP is required',
  new_password: 'Enter New Password',
  confirm_password: 'Enter Confirm Password',
  confirm_password_required: 'Confirm Password is required',
  new_password_required: 'New Password is required',
  password_mismatch: "Re-Enter password doesn't match New password",
  submit: 'Submit',
  communication_management: 'Communication Management',
  show_cause_notice: 'Show Cause Notice',
  application: 'Application',
  application_review_data: 'Application Review Data',
  no_application_found: 'No application data found',
  show_cause_notice_details: 'Show Cause Notice(s)',
  no_notice_found: 'No notice found',
  application_details: 'Application Review Details',
  download_gate_pass: 'Download Gate Pass',
  view_file: 'View File',
  show_cause_notice_edit: 'Show Cause Notice Edit',
  category: 'Category',
  title: 'Title',
  description: 'Description',
  date_of_notice: 'Date of Notice',
  status: 'Status',
  response: 'Response',
  response_required: 'Response is required',
  upload_file: 'Upload File',
  view_uploaded_file: 'View Uploaded File',
  choose_file: 'Choose File',
  add_pdf: 'Add PDF (max 3 MB)',
  no_file_available: 'No file available',
  file_size_exceeded: 'File size exceeds 3 MB. Please choose a smaller file.',
  file_selected: 'selected successfully!',
  file_pick_failed: 'Failed to pick file. Please try again.',
  response_submitted: 'Response submitted successfully!',
  something_went_wrong: 'Something went wrong while submitting.',
  my_profile: 'My Profile',
  profile: 'Profile',
  documents: 'Documents',
  indemnity_bond: 'Indemnity Bond',
  deactivate_account: 'Deactivate Account',
  deactivate_message: 'Are you sure you want to Deactivate Account?',
  deactivate_res_mess: 'Your account deactivate successfully',
  logout_message: 'Are you sure you want to logout?',
  logout: 'Logout',
  profile_details: 'Profile Details',
  trainee_id: 'Trainee ID',
  name_of_training_programme: 'Name of training programme',
  batch_no: 'Batch No',
  name: 'Name',
  course_duration: 'Course duration',
  aadhaar_no: 'Aadhaar No.',
  father_name: "Father's Name",
  gpf_pran: 'GPF/PRAN',
  pan_no: 'PAN No.',
  marital_status: 'Marital Status',
  unmarried: 'UnMarried',
  married: 'Married',
  gender: 'Gender',
  personal_email: 'Personal Email',
  office_email: 'Office Email',
  designation: 'Designation',
  mobile_no: 'Mobile No.',
  educational_qualification: 'Educational Qualification',
  office_address: 'Office Address',
  previous_work_experience: 'Previous work experience',
  residential_address: 'Residential Address',
  mother_name: "Mother's Name",
  na: 'N/A',
  to: 'To',
  download_and_print: 'Download and Print',
  edit: 'Edit',
  are_you_sure_print: 'Are You sure you want to print the application?',
  please_note: 'Please Note',
  registration_note: `1. Filling registration form and Indemnity bond is mandatory
2. You will need following documents to complete the process
   • Photo
   • Signature (.jpeg, .png format)
3. Details of two witnesses required:
   • Name
   • Designation
   • Signature (.jpeg, .png format)
4. Both documents must be filled at one time`,
  next: 'Next',
  something_went_wrong_: 'Something went wrong',
  indemnity_bond_form_title: 'Indemnity Bond Form',
  relation: 'Relation',
  relation_name: 'Relation Name',
  residence: 'Residence',
  employment_at: 'Employment At',
  duration: 'Duration',
  date: 'Date',
  month: 'Month',
  year: 'Year',
  campus: 'Campus',
  district: 'District',
  witness_name: 'Witness Name',
  signature_of_witness_bipard: 'Signature of Witness (BIPARD)',
  err_signature_of_witness_bipard: 'Signature of Witness (BIPARD) is required',
  preview: 'Preview',
  witness_designation_required: 'Witness designation is required',
  witness_name_required: 'Witness name is required',
  district_required: 'District is required',
  campus_required: 'Campus is required',
  relation_name_required: 'Relation Name is required',
  relation_required: 'Relation is required',
  empployme: 'Employme.',
  indemnity_bond_preview: 'Indemnity Bond Preview',
  indemnity_heading: 'GOOD BEHAVIOUR / INDEMNITY BOND BY TRAINEES',
  hindi_institute_title: 'बिहार लोक प्रशासन एवं ग्रामीण विकास संस्थान',
  hindi_address: 'कुशीधारा, गया - 823001',
  institute_full_name:
    'Bihar Institute of Public Administration & Rural Development',
  institute_address: 'Kushidhara, Gaya Jee - 823001',
  indemnifier_details: 'Indemnifier Details',
  witness_details_bipard: 'Witness Details (BIPARD)',
  name_of_indemnifier: 'Name of Indemnifier:',
  signature_of_indemnifier: '(Signature of Indemnifier)',
  signature_label: '(Signature)',
  no_file_uploaded: 'No File Uploaded',
  residence_of: 'Residence Of',
  employed_as_posted_at: 'employed as posted at',
  indemnity_clauses: [
    `I am aware of all the Government of India and State Acts/Laws/Regulations of the statutory bodies with respect to the Arms, Alcohols, Narcotics and Psychotropic Substances and other laws attracted in the event of any criminal offence committed by me during this training program. I shall not consume any tobacco, cigarette or other such substances during the training.`,
    `I will follow, abide and comply with all the directions given by officials, the course coordinator and the management of BIPARD.`,
    `In the event of residential training, I will not step outside the campus, in whatsoever situation, without having obtained due permission in written by the BIPARD. Nor will I keep/meet any person in my room.`,
    `I will keep my mobile phone/pager in silent mode. I shall not use mobile phone/pager during the training sessions and in the event of contravention of the same, the same shall be confiscated by the BIPARD for the remaining period of the training.`,
    `I will not cause any destruction or damage to any property of BIPARD intentionally or unintentionally and in case of such damage, I would be liable to be realized penalty against the same by the BIPARD.`,
    `At the time of breakfast, lunch, high tea and dinner, I shall remain present in the cafeteria/mess on the fixed time and I shall not waste food and in case of wastage of food, I shall be liable to be realized penalty against the same by the BIPARD.`,
    `I shall keep the premises of BIPARD clean, shall throw garbage only in dustbin and shall not litter anywhere and in the event of contravention of the same, I shall be liable to be realized penalty by the BIPARD.`,
    `I shall not step outside the classroom or roam around during the training sessions. During the tea break between the training sessions, I shall maintain silence and decorum of the classroom.`,
    `I will fully abide by the attendance rules and if I do not attend any training session without having obtained due permission by the BIPARD, I shall be liable to be punished as per due provisions.`,
    `In the event of residential training, while leaving the room, I shall switch off the lights, fans, AC etc. and in the event of contravention of the same, I shall be liable to be penalized by the BIPARD.`,
    `I shall follow the dress code as prescribed by BIPARD during the training and shall always carry my identity card issued by BIPARD.`,
    `During my stay in the hostel/campus, I shall not play loud music or any electronic device and maintain silence in the hostel.`,
    `I shall not engage myself in any tussle or fracas with any fellow trainee or staff at BIPARD.`,
    `I shall respect and regard all officials, faculties and resource persons of the BIPARD and shall not engage myself in any fracas with them.`,
    `I shall respect and regard other trainees, will not encroach upon their privacy and will maintain harmony and cordial relations with them.`,
    `I shall follow, abide and comply by all the rules, regulations and guidelines with regard to the training, hostel, discipline, training camps, trekking, yoga, meditation and exercises and other activities either conducted in physical or virtual mode as may be notified by BIPARD from time to time.`,
    `I have taken the required immunization, including for COVID-19 and I am not suffering from any communicable disease or any serious health illness, including mental illness. In case I am suffering from any illness, I would inform the course coordinator with regard to the same with complete details before the commencement of the training session and the decision of BIPARD in that regard shall be acceptable to me.`,
    `I will attend and participate in all the training sessions, physical exercises, outdoor excursions, yoga activities, sporting activities, cultural activities and such other activities within or outside the campus (including within or outside Bihar) at the fixed dates and time. I shall be willing to travel through such mode as decided by the BIPARD. I understand that the training program is rigorous and includes physical/mental exertion and therefore fully aware of the risks involved. I shall not hold BIPARD wholly or partly responsible in case of any accident, illness, injury or death.`,
    `I shall maintain the discipline, decorum, peace and tranquility at the premises of BIPARD and any loss and/or damages caused due to any undesirable action on my part would attract criminal prosecution/admissible claims/punishment/penalty as per the existing laws and procedures.`,
    `I also understand that, in case I break any of the above conditions, the BIPARD fully reserves the right to foreclose my training and send me back, apart from initiative such Departmental action as it may be deem fit.`,
    `I have no history of any serious physical or mental illness that would render me unfit for BIPARD training including physical training, Exposure visit etc. I have provided all information without withholding anything.`,
  ],
  indemnity_participation_prefix: 'hereby affirm that I am participating in',
  indemnity_program_commencing:
    'days/months training program voluntarily which is commencing from',
  indemnity_day_label: 'day',
  indemnity_month_label: 'month',
  indemnity_year_label: 'year',
  indemnity_scheduled_at:
    "scheduled to be conducted at Bihar Institute of Public Administration and Rural Development (hereinafter referred to as 'BIPARD') at campus",
  indemnity_and_declare:
    ', Bihar and do hereby undertake and declare the following:',
  document_details: 'Document Details',
  signature: 'Signature',
  photo: 'Photo',
  aadhar_card: 'Aadhar Card',
  no_documnet_available: 'No document available',

  /* Edit Profile screen strings */
  edit_profile: 'Edit Profile',
  date_of_birth: 'Date of Birth',
  other_email: 'Other Email',
  emergency_mobile: 'Emergency Mobile Number',
  pay_scale: 'Pay Scale',
  basic_pay_scale: 'Basic Pay Scale',
  office_district: 'Office District',
  office_pin_code: 'Office PIN Code',
  residential_district: 'Residential District',
  residential_pin_code: 'Residential PIN Code',
  doj_department: 'DOJ(Department)',
  doj_bipard: 'DOJ(BIPARD)',
  date_of_retirement: 'Date of Retirement(Job)',
  work_experience_details: 'Work Experience Details',
  computing_course_label:
    'Have you attended / completed any course on computing?',
  enter_details: 'Enter Details',
  knowledge_of_computing_label: 'Knowledge of computing, if any:',
  other_training_label:
    'Have you attended / completed any other training section?',
  upload_photo: 'Upload Photo',
  upload_signature: 'Upload Signature',
  upload_aadhar_card: 'Upload Aadhar Card',
  aadhar_merge_note: '* Note - Please merge aadhar front & back in one file',

  /* Validation / messages used in Edit Profile */
  details_is_required: 'Details is required',
  aadhar_card_required: 'Aadhar card is required',
  sign_required: 'Sign is required',
  photo_required: 'Photo is required',
  work_experience_details_required: 'Work Experience Details is required',
  date_of_retirement_required: 'Date of Retirement(Job) is required',
  doj_bipard_required: 'DOJ(BIPARD) is required',
  doj_department_required: 'DOJ(Department) is required',
  residential_pin_required: 'Residential PIN Code is required',
  enter_valid_residential_pin: 'Enter valid Residential PIN Code',
  residential_district_required: 'Residential District is required',
  residential_address_required: 'Residential Address is required',
  office_pin_required: 'Office PIN Code is required',
  enter_valid_office_pin: 'Enter valid Office pin code',
  office_district_required: 'Office District is required',
  office_address_required: 'Office Address is required',
  category_required: 'Category is required',
  basic_pay_required: 'Basic Pay Scale is required',
  pay_scale_required: 'Pay Scale is required',
  emergency_mobile_required: 'Emergency Mobile Number is required',
  enter_valid_emergency_mobile: 'Enter valid Emergency mobile number',
  qualification_required: 'Educatonal Qualification is required',
  mobile_required: 'Mobile Number is required',
  enter_valid_mobile: 'Enter valid mobile number',
  designation_required: 'Designation is required',
  office_email_required: 'Office email is required',
  enter_valid_email: 'Enter a Valid Email',
  dob_required: 'Date of Birth is required',
  gender_required: 'Gender is required',
  marital_status_required: 'Marital Status is required',
  pan_required: 'PAN is required',
  pan_invalid: 'Enter a Valid PAN Card Number',
  mother_name_required: 'Mother Name is required',
  father_name_required: 'Father Name is required',
  aadhar_required: 'Aadhar is required',
  aadhar_invalid: 'Enter The Correct Aadhaar Number',
  register_button: 'Register',

  /* Hostel Screens Strings */
  // AllHostel Screen
  allHostel: {
    hostelName: 'Hostel Name :',
    noOfFloors: 'No. of Floors :',
    noOfBeds: 'No. of Beds :',
    noOfRooms: 'No. of Rooms :',
    noOfVacant: 'No. of Vacant :',
    totalHostel: 'Total Hostel',
    totalRooms: 'Total Rooms',
    totalBeds: 'Total Beds',
    totalVacantBeds: 'Total Vacant Beds:',
    occupiedBeds: 'Occupied Beds:',
    date: 'Date',
    applyFilter: 'Apply Filter',
    clearFilter: 'Clear Filter',
    hideFilter: 'Hide Filter ▲',
    showFilter: 'Show Filter ▼',
    noDataFound: 'No Data Found',
  },

  // BlockDetails Screen
  blockDetails: {
    hostelDetails: 'Hostel Details',
    hostelDetailsOn: 'Hostel Details On',
    srNo: 'Sr.No:',
    purpose: 'Purpose:',
    type: 'Type:',
    hostel: 'Hostel:',
    from: 'From:',
    to: 'To:',
    blockedRooms: 'Blocked Rooms:',
    unblock: 'Unblock',
    noDataFound: 'No data found',
  },

  // BlockedForm Screen
  blockedForm: {
    hostelBlockRequest: 'Hostel Block Request',
    purpose: 'Purpose',
    blockType: 'Block Type',
    startDate: 'Start Date',
    endDate: 'End Date',
    hostel: 'Hostel',
    count: 'Count',
    block: 'Block',
    availableBeds: 'Available Beds:',
    addAnotherHostel: '+ Add Another Hostel',
    countLabel: 'Count:',
    remove: 'Remove',
    purposeRequired: 'Purpose is required',
    blockTypeRequired: 'Block Type is required',
    startDateRequired: 'Start date is required',
    endDateRequired: 'End date is required',
    addAtLeastOneHostel: 'Please add at least one hostel',
    selectHostel: 'Select Hostel',
    enterCount: 'Enter Count',
    hostelAlreadyAdded: 'Hostel already added',
  },

  // HostelDetailsDashboard Screen
  hostelDetailsDashboard: {
    noOfFloors: 'No of floors',
    noOfRooms: 'No of Rooms',
    noOfBeds: 'No of Beds',
    vacantBeds: 'Vacant Beds:',
    occupiedBeds: 'Occupied Beds:',
    floorName: 'Floor Name',
    roomNumber: 'Room Number',
    bedNumber: 'Bed Number:',
    from: 'From:',
    to: 'To:',
    training: 'Training:',
    noDataFound: 'No Data Found',
    noRoomAllocated: 'No Room Allocated',
    closeSymbol: '✕',
  },

  // HostelPlanning Screen
  hostelPlanning: {
    hostelBedsTotal: 'Hostel Beds (Total)',
    hostelBedsOccupied: 'Hostel Beds (Occupied)',
    guestBedsTotal: 'Guest Beds (Total)',
    guestBedsOccupied: 'Guest Beds (Occupied)',
    today: 'Today',
    block: 'Block',
    unblock: 'Unblock',
    arrowLeft: '◀',
    arrowRight: '▶',
  },

  // HostelPlanningDetails Screen
  hostelPlanningDetails: {
    hostelDetails: 'Hostel Details',
    hostelDetailsOn: 'Hostel Details On',
    srNo: 'Sr.No',
    hostelName: 'Hostel Name',
    room: 'Room',
    bed: 'Bed',
    trainingVacantBeds: 'Training Vacant Beds',
    guestVacantBeds: 'Guest Vacant Beds',
    noDataFound: 'No data found',
    dash: '-',
  },

  // HostelReport Screen
  hostelReport: {
    srNo: 'Sr. No',
    totalBed: 'Total Bed',
    hostelGuestHouseName: 'Hostel/Guest House Name',
    traineeAllocatedBed: 'Trainee Allocated Bed',
    guestAllocatedBed: 'Guest Allocated Bed',
    totalAllocatedBed: 'Total Allocated Bed',
    userType: 'User Type',
    training: 'Training',
    designation: 'Designation',
    startDate: 'Start Date',
    endDate: 'End Date',
    applyFilter: 'Apply Filter',
    clearFilter: 'Clear Filter',
    hideFilter: 'Hide Filter ▲',
    showFilter: 'Show Filter ▼',
    noDataFound: 'No Data Found',
  },

  // Vendor/InvoiceDashboard Screen
  vendor: {
    srNo: 'Sr. No:',
    name: 'Name',
    bipardCampus: 'Bipard Campus',
    totalInvoices: 'Total Invoices',
    pendingBills: 'Pending Bills',
    zeroToThreeDays: '0 – 3 Days',
    fourToSevenDays: '4 – 7 Days',
    eightToFifteenDays: '8 – 15 Days',
    moreThanFifteenDays: 'More than 15 Days',
    totalAmount: 'Total Amount (INR)',
    paidAmount: 'Paid Amount (INR)',
    unpaidAmount: 'Unpaid Amount (INR)',
    excel: 'Excel',
    pdf: 'Pdf',
    noDataFound: 'No data found',
  },

  // Dashboard Index Screen
  dashboardIndex: {
    hostelPlanning: 'Hostel Planning',
    hostelReport: 'Hostel Report',
    allHostel: 'All Hostel',
    hostel: 'Hostel',
    vendor: 'Vendor',
    centers: 'Centers',
    allCenters: 'All Centers',
    gaya: 'Gaya',
    patna: 'Patna',
    center: 'Center',
  },

  // Guest Management
  addGuest: {
    editGuest: 'Edit Guest',
    addGuest: 'Add Guest',
    genderRequired: 'Gender is required',
    mobileNumberRequired: 'Mobile number is required',
    officeEmailRequired: 'Office email is required',
    enterValidOfficeEmail: 'Enter valid office email',
    nameRequired: 'Name is required',
    bipardLocationRequired: 'Bipard location is required',
    bipardLocation: 'Bipard Location',
    name: 'Name',
    officeEmail: 'Office Email',
    mobileNumber: 'Mobile Number',
    designation: 'Designation',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    update: 'Update',
    add: 'Add',
  },
  guest: {
    guestList: 'Guest List',
    deleteConfirmation: 'Delete Confirmation',
    deleteItemConfirmation: 'Are you sure you want to delete this item?',
    confirm: 'Confirm',
    srNo: 'Sr. No:',
    guestId: 'Guest ID',
    name: 'Name',
    mobileNumber: 'Mobile Number',
    gender: 'Gender',
    officeEmail: 'Office Email',
    designation: 'Designation',
    noDataFound: 'No data found',
  },

  // Hostel Management
  hostelManagement: {
    // Common strings
    srNo: 'Sr. No:',
    noDataFound: 'No data found',
    deleteConfirmation: 'Delete Confirmation',
    statusChangeConfirmation: 'Status Change Confirmation',
    deleteItemConfirmation: 'Are you sure you want to delete this item?',
    statusChangeMessage: 'Are you sure you want to change this item?',
    confirm: 'Confirm',
    active: 'Active',
    inActive: 'In-Active',
    status: 'Status',

    // Hostel Details
    hostelDetails: {
      title: 'Hostel Details',
      trainingCentre: 'Training Centre',
      hostelName: 'Hostel Name',
      noOfFloors: 'No Of Floors',
      hostelAddress: 'Hostel Address',
      contactPerson: 'Contact Person',
      contactNo: 'Contact No',
      alternateContactNo: 'Alternate Contact No',
    },

    // Floor Details
    floorDetails: {
      title: 'Floor Details',
      floorName: 'Name of Floors',
      floorNumber: 'Floor Number',
      floorType: 'Floor Type',
      hostelName: 'Hostel Name',
      noOfRooms: 'No of Rooms',
      filterOptions: 'Filter Options',
      selectHostelMessage: 'Please select a hostel',
      applyFilter: 'Apply Filter',
      clearFilter: 'Clear Filter',
      hideFilter: 'Hide Filter ▲',
      showFilter: 'Show Filter ▼',
    },

    // Room Details

    // Bed Details
    bedDetails: {
      title: 'Bed Details',
      bedNumber: 'Bed Number',
      bedName: 'Bed Name',
      roomNumber: 'Room Number',
      roomNo: 'Room No',
      floorName: 'Floor Name',
      hostelName: 'Hostel Name',
      bedType: 'Bed Type',
      roomName: 'Room Name',
      status: 'Status',
      active: 'Active',
      inActive: 'In-Active',
      statusChangeConfirmation: 'Status Change Confirmation',
      statusChangeMessage: 'Are you sure you want to change this item?',
      deleteConfirmation: 'Delete Confirmation',
      deleteMessage: 'Are you sure you want to delete this item?',
    },

    // Bed Availability
    bedAvailability: {
      title: 'Bed Availability Details',
      availableBeds: 'Available Beds',
      occupiedBeds: 'Occupied Beds',
      totalBeds: 'Total Beds',
      hostelName: 'Hostel Name',
      hostel: 'Hostel',
      floorName: 'Floor Name',
      floor: 'Floor',
      roomNumber: 'Room Number',
      room: 'Room',
      bedNumber: 'Bed Number',
      bed: 'Bed',
      bedStatus: 'Status',
      vacant: 'Vacant',
      allocated: 'Allocated',
      blocked: 'Blocked',
      startDate: 'Start Date',
      endDate: 'End Date',
      applyFilter: 'Apply Filter',
      clearFilter: 'Clear Filter',
      hideFilter: 'Hide Filter ▲',
      showFilter: 'Show Filter ▼',
    },

    // Add Bed Details
    addBedDetails: {
      editTitle: 'Edit Bed Details',
      addTitle: 'Add Bed Details',
      bipardLocation: 'Bipard Location',
      hostelName: 'Hostel Name',
      floorName: 'Floor Name',
      room: 'Room',
      bedName: 'Bed Name',
      status: 'Status',
      active: 'Active',
      inactive: 'Inactive',
      update: 'Update',
      add: 'Add',
      required: {
        status: 'Status is required',
        bedName: 'Bed name is required',
        room: 'Room is required',
        floor: 'Floor name is required',
        hostel: 'Hostel name is required',
        location: 'Bipard location is required',
      },
      success: {
        added: 'Bed details added successfully',
        updated: 'Bed details updated successfully',
      },
    },

    // Add Floor Details
    addFloorDetails: {
      editTitle: 'Edit Floor Details',
      addTitle: 'Add Floor Details',
      floorGenderType: 'Floor Gender Type',
      nameOfFloor: 'Name Of Floor',
      noOfRooms: 'No Of Rooms',
      required: {
        noOfRooms: 'Number of room is required',
        nameOfFloor: 'Name of floor is required',
        genderType: 'Floor gender type is required',
      },
    },

    // Add Hostel Details
    addHostelDetails: {
      editTitle: 'Edit Hostel',
      addTitle: 'Add Hostel',
      hostelAddress: 'Hostel Address',
      noOfFloor: 'No Of Floor',
      contactPerson: 'Contact Person',
      contactNumber: 'Contact Number',
      totalCapacity: 'Total Capacity',
      trainingCenter: 'Training Center',
      alternateContactNo: 'Alternate Contact Number',
      enterTenDigit: 'Enter 10 digit number',
      errors: {
        duplicateAlternate: 'Alternate numbers cannot be same',
        sameAsMain: 'Alternate number cannot be same as Contact Number',
        maxAlternate: 'You can add only 2 alternate contact numbers',
        fillFirst:
          'Please fill the first alternate number before adding another',
        validContact: 'Enter valid contact number',
      },
      required: {
        totalCapacity: 'Total capacity is required',
        contactNumber: 'Contact Number is required',
        contactPerson: 'Contact person is required',
        hostelAddress: 'Hostel Address is required',
      },
    },

    // Hostel Allocation
    hostelAllocation: {
      title: 'Hostel Allocation',
      srNo: 'Sr. No:',
      trainingProgramme: 'Training Programme',
      courseStartDate: 'Course Start Date',
      courseEndDate: 'Course End Date',
      hostel: 'Hostel',
      room: 'Room',
      bed: 'Bed',
      allocate: 'Allocate',
      name: 'Name',
      email: 'Email',
      mobileNumber: 'Mobile Number',
      key: 'Key',
      yogaMat: 'Yoga Mat',
      deleteConfirmation: 'Delete Confirmation',
      deleteMessage: 'Are you sure you want to delete this item?',
      confirm: 'Confirm',
      trainingDetail: 'Training Detail',
      allocationStatus: 'Allocation Status',
      gender: 'Gender',
      applyFilter: 'Apply Filter',
      clearFilter: 'Clear Filter',
      showFilter: 'Show Filter ▼',
      hideFilter: 'Hide Filter ▲',
      trainee: 'Trainee',
      guest: 'Guest',
      allocationDetails: 'Allocation Details',
      keyProvided: 'Key Provided',
      yogaMatProvided: 'Yoga Mat Provided',
      allocatedRoom: 'Allocated Room',
      newRoom: 'New Room',
      allocatedBed: 'Allocated Bed',
      newBed: 'New Bed',
      purpose: 'Purpose',
      submit: 'Submit',
      hostelAllocationRequest: 'Hostel Allocation Request',
      guestIdOrEmail: 'Guest Id / Email Id',
      checkInDate: 'Check In Date',
      checkOutDate: 'Check Out Date',
      validIdError: 'Enter valid Email or Guest Id',
      required: {
        purpose: 'Purpose is required',
        newBed: 'New bed is required',
        newRoom: 'New room is required',
        hostel: 'Hostel is required',
        yogaMatProvided: 'Yoga Mat Provided is required',
        keyProvided: 'Key Provided is required',
        checkOutDate: 'Check out date is required',
        checkInDate: 'Check in date is required',
        gender: 'Gender is required',
        guestId: 'Guest Id / Email Id is required',
      },
      yes: 'Yes',
      no: 'No',
      aadhaarNumber: 'Aadhaar Number',
      panNumber: 'PAN Number',
      department: 'Department',
      noOfDays: 'No Of Days',
      photo: 'Photo',
      signature: 'Signature',
    },

    // Hostel Allocation History
    hostelAllocationHistory: {
      title: 'Hostel Allocation History',
      srNo: 'Sr. No:',
      trainingProgramme: 'Training Programme',
      courseStartDate: 'Course Start Date',
      courseEndDate: 'Course End Date',
      hostel: 'Hostel',
      room: 'Room',
      bed: 'Bed',
      name: 'Name',
      email: 'Email',
      mobileNumber: 'Mobile Number',
      trainingDetail: 'Training Detail',
      gender: 'Gender',
      startDate: 'Start Date',
      endDate: 'End Date',
      applyFilter: 'Apply Filter',
      clearFilter: 'Clear Filter',
      showFilter: 'Show Filter ▼',
      hideFilter: 'Hide Filter ▲',
      download: 'Download',
      noDataFound: 'No data found',
      allocationDetails: 'Allocation Details',
      aadhaarNumber: 'Aadhaar Number',
      panNumber: 'PAN Number',
      department: 'Department',
      noOfDays: 'No Of Days',
    },

    // Hostel Menu
    hostelMenu: {
      title: 'Hostel Management',
      hostelDetails: 'Hostel Details',
      floorDetails: 'Floor Details',
      roomDetails: 'Room Details',
      bedDetails: 'Bed Details',
      hostelAllocation: 'Hostel Allocation',
      hostelAllocationHistory: 'Hostel Allocation History',
      bedAvailability: 'Bed Availability',
      guest: 'Guest',
      hostel: 'Hostel',
    },
    // Room Details
    roomDetails: {
      title: 'Room Details',
      hostelName: 'Hostel Name',
      floorName: 'Floor Name',
      roomNo: 'Room No',
      noOfBed: 'No Of bed',
      roomType: 'Room Type',
      status: 'Status',
      active: 'Active',
      inactive: 'Inactive',
      applyFilter: 'Apply Filter',
      clearFilter: 'Clear Filter',
      showFilter: 'Show Filter ▼',
      hideFilter: 'Hide Filter ▲',
      noDataFound: 'No data found',
      floor: 'Floor',
      hostel: 'Hostel',
      statusChange: {
        title: 'Status Change Confirmation',
        message: 'Are you sure you want to change this item?',
        confirm: 'Confirm',
      },
      roomTypeChange: {
        title: 'Room Type Change Confirmation',
        message: 'Are you sure you want to change room type this item?',
        confirm: 'Confirm',
      },
      delete: {
        title: 'Delete Confirmation',
        message: 'Are you sure you want to delete this item?',
        confirm: 'Confirm',
      },
      dropdown: {
        trainee: 'Trainee',
        guest: 'Guest',
        hostel: 'Hostel', // Added 'hostel' here
      },
    },
    // Add Room Details
    addRoomDetails: {
      editTitle: 'Edit Room Details',
      addTitle: 'Add Room Details',
      bipardLocation: 'Bipard Location',
      hostelName: 'Hostel Name',
      floorName: 'Floor Name',
      roomNumber: 'Room Number',
      noOfBed: 'No Of Bed',
      status: 'Status',
      active: 'Active',
      inactive: 'Inactive',
      update: 'Update',
      add: 'Add',
      required: {
        status: 'Status is required',
        noOfBed: 'Number of bed is required',
        roomNo: 'Room no is required',
        floorName: 'Floor name is required',
        hostelName: 'Hostel name is required',
        bipardLocation: 'Bipard location is required',
      },
    },
  },

  // Assignment Strings
  assignment: {
    assignQuestionDetails: 'Assign Question Details',
    assignmentName: 'Assignment Name',
    topic: 'Topic',
    faculty: 'Faculty',
    questionType: 'Question Type',
    questionBankDetails: 'Question Bank Details',
    subject: 'Subject',
    noOfQuestions: 'No. of Questions',
    mcq: 'MCQ',
    subjective: 'Subjective',
    noMcqFound: 'No MCQ found',
    noSubjectiveQuestionsFound: 'No subjective questions found',
    marks: 'Marks',
    assignment: 'Assignment',
    assignQuestion: 'Assign Question',
    assignmentsDetails: 'Assignments Details',
    assignmentsResponse: 'Assignments Response',
    question: 'Question',
  },

  lms: {
    assignmentResponse: {
      title: 'Assignments Response',
      srNo: 'Sr. No:',
      trainingName: 'Training Name',
      totalAssignment: 'Total Assignment',
      center: 'Center',
      centers: 'Centers',
      noDataFound: 'No data found',
      traineeName: 'Trainee Name',
      batchNo: 'Batch No',
      assignmentName: 'Assignment Name',
      submissionDate: 'Submission Date',
      assignmentStatus: 'Assignment Status',
      batch: 'Batch',
      startDate: 'Start Date',
      endDate: 'End Date',
      applyFilter: 'Apply Filter',
      clearFilter: 'Clear Filter',
      showFilter: 'Show Filter',
      hideFilter: 'Hide Filter',
      submitted: 'Submitted',
      notSubmitted: 'Not submitted',
      submittedWaiting: 'Submitted waiting for grading',
    },
    assignmentDetails: {
      title: 'Assignments Details',
      center: 'Center',
      centers: 'Centers',
      show: 'Show',
      hide: 'Hide',
      trainingName: 'Training Name',
      totalAssignment: 'Total Assignment',
    },
    assessmentDetails: {
      title: 'Assignment Details',
      mcq: 'MCQ',
      subjective: 'Subjective',
      marks: 'Marks',
      ans: 'Ans:',
      openFile: 'OPEN FILE',
      assignmentName: 'Assignment Name:',
      traineeName: 'Trainee Name / Group Name:',
      availability: 'Availability:',
      submittedOn: 'Submitted On:',
    },
    assignmentDetailsList: {
      title: 'Assignments Details List',
      noOfQuestions: 'No Of Questions',
      submissionType: 'Submission Type',
      startDate: 'Start Date',
      endDate: 'End Date',
      status: 'Status',
      statusChangeConf: 'Status Change Confirmation',
      statusChangeMsg: 'Are you sure you want to change this item?',
      confirm: 'Confirm',
      assignmentName: 'Assignment Name',
    },
    locationDetails: {
      title: 'Location Details',
      classLocationManagementTitle: 'Class Location Management',
      subLocationDetailsTitle: 'Sub Location Details',
      locationName: 'Location Name',
      address: 'Address',
      street: 'Street',
      selectCity: 'Select City',
      pinCode: 'PIN Code',
      contactPerson: 'Contact Person',
      contactNo: 'Contact No',
      alternateContactNo: 'Alternate Contact No',
      emailId: 'Email ID',
      status: 'Status',
      facultyType: 'Faculty Type',
      department: 'Department',
      organisation: 'Organisation',
      applyFilter: 'Apply Filter',
      clearFilter: 'Clear Filter',
      deleteConfirmation: 'Delete Confirmation',
      deleteMsg: 'Are you sure you want to delete this item?',
      confirm: 'Confirm',
      selectLocationName: 'Select Location Name',
      subLocationName: 'Sub Location Name',
      totalCapacity: 'Total Capacity',
      srNo: 'Sr. No.',
      centers: 'Centers',
      noDataFound: 'No data found',
    },
    classRoomManagement: {
      title: 'Class Room Management',
      timeTable: 'Time Table',
      facultyClassApprove: 'Faculty Class Approve',
      timeTableData: 'Time Table Data',
      currentTraining: 'Current Training',
      previousTraining: 'Previous Training',
      noOfClasses: 'No of Classes',
      trainingEnd: 'TRAINING END',
      bipardLocation: 'Bipard Location',
      trainingName: 'Training Name',
      batchName: 'Batch Name',
      startDate: 'Start Date',
      endDate: 'End Date',
      duration: 'Duration',
      days: 'Days',
      session: 'Session',
      subject: 'Subject',
      topic: 'Topic',
      faculty: 'Faculty',
      fId: 'F ID',
      vc: 'VC',
      isClassPhotoUploaded: 'Is Class Photo Uploaded',
      vehicle: 'Vehicle',
      uploadViewPhoto: 'Upload / View Photo',
      batchNo: 'Batch No',
      dateIsRequired: 'Date is required',
      extend: 'Extend',
      extendedDate: 'Extended Date',
      extendDateOf: 'Extend Date of',
      unselectAll: 'Unselect All',
      selectAll: 'Select All',
      selectToDownload: 'Select to download',
      hideFilter: 'Hide Filter ▲',
      showFilter: 'Show Filter ▼',
      fileNoNotEmpty: 'File No cannot be empty!',
      errorUpdatingFileNo: 'Error updating File No',
    },
    curriculumManagement: {
      title: 'Curriculum Management',
      subjectDetails: 'Subject Details',
      subjectTopicDetails: 'Subject Topic Details',
      subject: 'Subject',
      description: 'Description',
      thumbnail: 'Thumbnail',
      facultyType: 'Faculty Type',
      department: 'Department',
      organisation: 'Organisation',
      userType: 'User Type',
      applyFilter: 'Apply Filter',
      clearFilter: 'Clear Filter',
      noDataFound: 'No data found',
      srNo: 'Sr. No:',
    },
    examination: {
      assignQuestionList: {
        title: 'Assign Question Details',
        testName: 'Test Name',
        topic: 'Topic',
        questionType: 'Question Type',
        questionRandomization: 'Question Randomization',
        randomizeQuestionsConf: 'Randomize Questions Confirmation',
        randomizeQuestionsMsg:
          'Are you sure you want to randomize questions for this assessment?',
        confirm: 'Confirm',
        noDataFound: 'No data found',
        srNo: 'Sr. No:',
      },
      testDetails: {
        title: 'Test Details',
        trainingName: 'Training Name',
        totalAssignment: 'Total Assignment',
        noDataFound: 'No data found',
        srNo: 'Sr. No:',
      },
      testDetailsList: {
        title: 'Test Details List',
        testName: 'Test Name',
        noOfQuestions: 'No Of Questions',
        testType: 'Test Type',
        testStartDate: 'Test Start Date',
        testEndDate: 'Test End Date',
        timeLimit: 'Time Limit',
        negativeMarking: 'Negative Marking',
        status: 'Status',
        statusChangeConf: 'Status Change Confirmation',
        statusChangeMsg: 'Are you sure you want to change this item?',
        confirm: 'Confirm',
        noDataFound: 'No data found',
        srNo: 'Sr. No:',
      },
      examinationIndex: {
        title: 'Examination',
        createTest: 'Create Test',
        assignQuestion: 'Assign Question',
        question: 'Question',
        examResponse: 'Exam Response',
      },
      questionBank: {
        title: 'Question Bank',
        subject: 'Subject',
        topic: 'Topic',
        noOfQuestions: 'No. of Questions',
        noDataFound: 'No data found',
        srNo: 'Sr. No:',
      },
      questionBankDetails: {
        title: 'Question Bank Details',
        subject: 'Subject:',
        topic: 'Topic:',
        mcq: 'MCQ',
        subjective: 'Subjective',
        noMcqFound: 'No MCQ found',
        noSubjectiveFound: 'No subjective questions found',
        marks: 'Marks',
      },
      examResponse: {
        title: 'Examination List',
        trainingName: 'Training Name',
        examinationName: 'Examination Name',
        examinationDate: 'Examination Date',
        srNo: 'Sr. No:',
        noDataFound: 'No data found',
      },
      examResponseDetails: {
        title: 'Exam Response Details',
        trainingName: 'Training Name',
        traineeName: 'Trainee Name',
        traineeEmail: 'Trainee Email',
        traineeBatchNo: 'Trainee Batch No',
        examName: 'Exam Name',
        attempt: 'Attempt',
        totalQuestions: 'Total Questions',
        totalMarks: 'Total Marks',
        passingMarks: 'Passing Marks',
        obtainedMarks: 'Obtained Marks',
        status: 'Status',
        finalSubmission: 'Final Submission',
      },
      traineeResponseList: {
        title: 'Exam Response Details',
        viewResponse: 'View Response',
        trainingName: 'Training Name',
        traineeName: 'Trainee Name',
        batchNo: 'Batch No',
        examName: 'Exam Name',
        batch: 'Batch',
        result: 'Result',
        fail: 'Fail',
        pass: 'Pass',
        applyFilter: 'Apply Filter',
        clearFilter: 'Clear Filter',
        hideFilter: 'Hide Filter ▲',
        showFilter: 'Show Filter ▼',
        noDataFound: 'No data found',
        srNo: 'Sr. No:',
      },
      examResponseSheet: {
        title: 'Responses List',
        selectedAnswer: 'Selected Answer: ',
        correctAnswer: 'Correct Answer: ',
        noResponsesFound: 'No responses found',
      },
    },
    facultyManagement: {
      facultyClassReportFeedback: {
        main: {
          title: 'Faculty Feedback Report',
          facultyName: 'Faculty Name',
          classCount: 'Class Count',
          rating: 'Rating',
          averageRating: 'Average Rating',
          srNo: 'Sr. No:',
          noDataFound: 'No data found',
          faculty: 'Faculty',
          centers: 'Centers',
          center: 'Center',
          applyFilter: 'Apply Filter',
          clearFilter: 'Clear Filter',
          hideFilter: 'Hide Filter ▲',
          showFilter: 'Show Filter ▼',
        },
        subject: {
          title: 'Faculty Subject Feedback',
          subjectName: 'Subject Name',
          classCount: 'Class Count',
          averageRating: 'Average Rating',
          srNo: 'Sr. No:',
        },
        topic: {
          title: 'Faculty Topic Feedback',
          subjectName: 'Subject Name',
          classCount: 'Class Count',
          averageRating: 'Average Rating',
          srNo: 'Sr. No:',
        },
        traineeDetail: {
          title: 'Topic Rating Details',
          srNo: 'Sr. No',
          rating: 'Rating',
          traineeCount: 'Trainee Count',
          feedbackHeading: 'Feedback given by following Trainee',
          traineeName: 'Trainee Name',
          trainingName: 'Training Name',
          batchNo: 'Batch No',
          noDataFound: 'No data found',
        },
      },
      main: {
        title: 'Faculty Management',
        facultyDetails: 'Faculty Details',
        facultyConfirmation: 'Faculty Confirmation',
        facultyFeedback: 'Faculty Class Report Feedback',
      },
      confirmation: {
        class:"Class",
        title: 'Faculty Confirmation',
        detailsTitle: 'Faculty Details',
        facultyName: 'Faculty Name',
        trainingName: 'Training Name',
        subject: 'Subject',
        topic: 'Topic',
        classDate: 'Class Date',
        sessionTime: 'Session Time',
        email: 'E-Mail',
        mobileNumber: 'Mobile Number',
        classApproved: 'Class Approved',
        classConfirmation: 'Class Confirmation',
        srNo: 'Sr. No:',
        confirm: 'Confirm',
        cancel: 'Cancel',
        statusChangeConf: 'Class Confirmation',
        statusChangeMsg: 'Are you sure you want to change the confirmation?',
        noDataFound: 'No data found',
      },
      details: {
        title: 'Faculty Details',
        addTitle: 'Add Faculty Details',
        editTitle: 'Edit Faculty Details',
        facultyUID: 'Faculty U.ID',
        facultyId: 'Faculty Id',
        facultyType: 'Faculty Type',
        facultyOrganisation: 'Faculty Organisation',
        facultyName: 'Faculty Name',
        name: 'Name',
        designation: 'Designation',
        department: 'Department',
        email: 'Email ID',
        mobileNumber: 'Mobile Number',
        state: 'State',
        outsideBiharState: 'Outside Bihar State',
        payLevel: 'BIPARD Pay Level',
        remuneration: 'Remuneration',
        category: 'Category',
        status: 'Status',
        blockUnblock: 'Block / Unblock',
        pan: 'PAN',
        bankName: 'Bank Name',
        branchName: 'Branch Name',
        accountHolder: 'Account Holder',
        accountNo: 'Account No',
        ifscCode: 'IFSC Code',
        expertise: 'Faculty Subject / Expertise',
        createdBy: 'Created By',
        updatedBy: 'Updated By',
        location: 'Location',
        bihar: 'Bihar',
        outsideBihar: 'Outside Bihar',
        uploadFile: 'Upload File',
        addFile: 'NOTE: Please merge proof document front and back side in single file before uploading if applicable',
        chooseFile: 'Choose File',
        add: 'Add',
        update: 'Update',
        active: 'Active',
        inactive: 'Inactive',
        inActive: 'In-Active',
        srNo: 'Sr. No:',
        noDataFound: 'No data found',
        applyFilter: 'Apply Filter',
        clearFilter: 'Clear Filter',
        hideFilter: 'Hide Filter ▲',
        showFilter: 'Show Filter ▼',
        statusChangeConf: 'Status Change Confirmation',
        deleteConf: 'Delete Confirmation',
        statusChangeMsg: 'Are you sure you want to change this item?',
        deleteMsg: 'Are you sure you want to delete this item?',
        confirm: 'Confirm',
        bipardLocation: 'Bipard Location',
        salutation: 'Salutation',
        panNumber: 'Pan Number',
      },
      validation: {
        statusRequired: 'Status is required',
        documentRequired: 'Document is required',
        stateRequired: 'State is required',
        locationRequired: 'Location is required',
        panRequired: 'Pan Number is required',
        panDigits: 'Pan number must be 10 digits',
        payLevelRequired: 'BIPARD pay level is required',
        categoryRequired: 'Category is required',
        mobileRequired: 'Mobile Number is required',
        mobileDigits: 'Mobile number must be 10 digits',
        emailRequired: 'Email is required',
        facultyNameRequired: 'Faculty name is required',
        salutationRequired: 'Salutation is required',
        bipardLocationRequired: 'Bipard location is required',
        facultyTypeRequired: 'Faculty type is required',
      },
    },
  },
  pharmacy_module: 'Pharmacy Module',
  medicine_type: 'Medicine Type',
  patients: 'Patients',
  pharmacy_master: 'Pharmacy Master',
  stock_report: 'Stock Report',
  update_stock: 'Update Stock',
  patient_details: 'Patient Details',
  sr_no: 'Sr. No:',
  no_data_found: 'No data found',
  all_centers: 'All Centers',
  centers: 'Centers',
  patients_details: 'Patients Details',
  month_year: 'Month & Year',
  training_name: 'Training Name',
  blood_group: 'Blood Group',
  age: 'Age',
  temperature: 'Temperature (°C)',
  blood_pressure: 'Blood Pressure',
  weight: 'Weight (kg)',
  primary_observations: 'Primary Observations',
  assigned_doctor: 'Assigned Doctor',
  treatment_types: 'Treatment Types',
  medicines: 'Medicines',
  dose: 'Dose',
  count: 'Count',
  view_prescription: 'View Prescription',
  no_medicines: 'No Medicines',
  symptom_id: 'Symptom ID',
  patient_type: 'Patient Type',
  unique_id: 'Unique ID',
  pharmacy: 'Pharmacy',
  medicine_name: 'Medicine Name',
  composition: 'Composition',
  mrp: 'MRP',
  unit: 'Unit',
  manufacturing_date: 'Manufacturing Date',
  expiry_date: 'Expiry Date',
  batch: 'Batch',
  medicine_unit: 'Medicine Unit',
  stock: 'Stock',
  total_unit: 'Total Unit',
  center: 'Center',
  medicine: 'Medicine',
  start_date: 'Start Date',
  end_date: 'End Date',
  apply_filter: 'Apply Filter',
  clear_filter: 'Clear Filter',
  show_filter: 'Show Filter ▼',
  hide_filter: 'Hide Filter ▲',
  apply_month_year_filter_before_downloading:
    'Apply Month & Year filter before downloading',
  apply_at_least_one_filter_before_downloading:
    'Apply at least one filter before downloading',
};
