export default {
  app_name: 'BIPARD ERP',
  select: 'Select',
  search: 'Search',
  noDataFound: 'No Data Found',
  done: 'Done',
  ok: 'Ok',
  cancel: 'Cancel',
  noInternet: 'No Internet',
  noInternetMessage:
    'No internet connection was found. Please check your connection or try again',
  tryAgain: 'Try again',
  remember_me: 'Remember me',
  bipard: 'Bihar Institute of Public Administration & Rural Development',
  welcome_to_bipard_erp: 'Welcome to BIPARD ERP!',
  sign_in: 'Sign In',
  message_1:
    "Training is a process by which officials' abilities are increased to perform specific tasks. Inspired by the changing global norms as per the social demands, training is an opportunity to move forward on the path of progress and deal with the challenges faced by society, which lacks negativity and is full of positivity. Through training, government talents are integrated into the mainstream of the nation's development by ensuring the necessary security and rights of citizens with transparency. It should be the duty of every public servant to try to incorporate the processes of discipline in his life and use them responsibly in public life - the inclusion of this process in training is necessary.",
  message_2:
    'Training of officials and employees does not only mean giving information about the requirements and techniques coming into their work area. Although all these dimensions are important parts and components of training, training is an essential process of developing the complete personality of the trainees. It is a verified fact that the process of selection of administrative officers is long and difficult and the people who are successfully selected in this selection process have special talent and knowledge of the subject. Therefore, in addition to the education related to the work techniques of the officials in the training institute, the focus should be on the overall development of their personality. To give a real shape to this principle, in addition to regular academic training, the trainees in Bipard are given physical education and yoga education, sports, etc.',
  message_3:
    'Special attention is given. Besides, arrangements are also made for India darshan, trekking and mountaineering, adventure travel etc. to enhance the knowledge of the officials. Team spirit and leadership skills are developed through these external and extracurricular activities.',
  message_4:
    "The publication of the magazine 'Unnayan', which embodies the monthly presentation of this institute, has fully contributed to its development. All the officers and other employees involved in this are making full use of their will and are witnessing its progress. The writings of various scholars on various subjects have made it mature.",
  message_5:
    'In the last year, BIPARD has created a unique identity for itself due to new applications related to training and innovations in administrative training. Bihar Government implements training with new consciousness through experiments based on new research to meet the demand of its various departments as per the requirement. BIPARD is showing a unique example of success by delivering quality training to many training programs despite short notice.',
  message_6:
    "Apart from training on administration and departmental subjects, the subject that is most needed in training modules today is discipline. Administrative discipline is not only indispensable in the achievement of organizational objectives but is also essential in personal life. In times of erosion of discipline, transplantation, promotion, and establishment of discipline have become the main objective and subject of BIPARD training, this training is proving to be universal. Without discipline all qualities become useless. To prove the proverb 'Multiple dishes without salt, BIPARD starts practicing physical exercises and yoga at 5.30 in the morning to inculcate discipline among the trainees. The fatigue and stress of continuous study throughout the day go away in the evening yoga practice. This creates awareness about discipline among the trainees and develops a feeling of cooperation, tolerance, participation, and adjustment. After accepting the bondage of discipline, they find it easier to execute administrative work with commitment and dedication. Administrative discipline holds its special place in the execution of time-bound tasks like law and order, disaster management, elections, etc. because these tasks require a specific work system instead of a general work system. This nature and diversity of training differentiates BIPARD trainees from other trainees. The trainees, after receiving training here, become completely disciplined and dedicate themselves to public service in the spirit of public welfare, that is why BIPARD focus is especially on discipline.",
  message_7:
    "Education is the backbone of the country's development. With the right direction of education, proper use of technologies becomes possible and new technologies are developed. It is well known that teachers are the builders of the nation. To implement this, this development yagya has been started by training the administrative officers and employees as well as teachers through BIPARD. The officers, employees and other people involved in raising BIPARD to great heights with their multifaceted service deserve congratulations. 'Unnayan' is succeeding in its objective by communicating this. Best wishes for its presentation.",
  dg_message: 'DG Message',
  dg_name: 'Dr. B. Rajender (IAS)',
  dg_designation: 'Director General, BIPARD',
  read_more: '...Read More',
  event_calendar: 'Event Calendar',
  this_month_event: 'This Month Event',
  notice: 'Notice',
  new_notice_found: 'New Notice(s) Found',
  no_new_notice_found: 'No New Notice Found',
  no_record_found: 'No record found',
  close: 'Close',
  username: 'Username',
  password: 'Password',
  role_required: 'Role is required',
  username_required: 'Username is required',
  password_required: 'Password is required',
  sign_in_button: 'Sign In',
  download_manual: 'Download User Manual for ADMIN',
  forgot_password: 'Forgot Password?',
  copyright: '© 2025 BIPARD',
  designed_by: 'Designed and Developed By',
  codebucket: 'Codebucket Solutions Private Limited',
  forgot_password_title: 'Forgot Password',
  otp: 'OTP',
  otp_required: 'OTP is required',
  new_password: 'Enter New Password',
  confirm_password: 'Enter Confirm Password',
  confirm_password_required: 'Confirm Password is required',
  new_password_required: 'New Password is required',
  password_mismatch: "Re-Enter password doesn't match New password",
  submit: 'Submit',
  communication_management: 'Communication Management',
  show_cause_notice: 'Show Cause Notice',
  application: 'Application',
  application_review_data: 'Application Review Data',
  no_application_found: 'No application data found',
  show_cause_notice_details: 'Show cause Notice Details',
  no_notice_found: 'No notice found',
  application_details: 'Application Review Details',
  download_gate_pass: 'Download Gate Pass',
  view_file: 'View File',
  show_cause_notice_edit: 'Show Cause Notice Edit',
  category: 'Category',
  title: 'Title',
  description: 'Description',
  date_of_notice: 'Date of Notice',
  status: 'Status',
  response: 'Response',
  response_required: 'Response is required',
  upload_file: 'Upload File',
  view_uploaded_file: 'View Uploaded File',
  choose_file: 'Choose File',
  add_pdf: 'Add PDF (max 3 MB)',
  no_file_available: 'No file available',
  file_size_exceeded: 'File size exceeds 3 MB. Please choose a smaller file.',
  file_selected: 'selected successfully!',
  file_pick_failed: 'Failed to pick file. Please try again.',
  response_submitted: 'Response submitted successfully!',
  something_went_wrong: 'Something went wrong while submitting.',
  my_profile: 'My Profile',
  profile: 'Profile',
  documents: 'Documents',
  indemnity_bond: 'Indemnity Bond',
  deactivate_account: 'Deactivate Account',
  deactivate_message: 'Are you sure you want to Deactivate Account?',
  deactivate_res_mess: 'Your account deactivate successfully',
  logout_message: 'Are you sure you want to logout?',
  logout: 'Logout',
  profile_details: 'Profile Details',
  trainee_id: 'Trainee ID',
  name_of_training_programme: 'Name of training programme',
  batch_no: 'Batch No',
  name: 'Name',
  course_duration: 'Course duration',
  aadhaar_no: 'Aadhaar No.',
  father_name: "Father's Name",
  gpf_pran: 'GPF/PRAN',
  pan_no: 'PAN No.',
  marital_status: 'Marital Status',
  unmarried: 'UnMarried',
  married: 'Married',
  gender: 'Gender',
  personal_email: 'Personal Email',
  office_email: 'Office Email',
  designation: 'Designation',
  mobile_no: 'Mobile No.',
  educational_qualification: 'Educational Qualification',
  office_address: 'Office Address',
  previous_work_experience: 'Previous work experience',
  residential_address: 'Residential Address',
  mother_name: "Mother's Name",
  na: 'N/A',
  to: 'To',
  download_and_print: 'Download and Print',
  edit: 'Edit',
  are_you_sure_print: 'Are You sure you want to print the application?',
  please_note: 'Please Note',
  registration_note: `1. Filling registration form and Indemnity bond is mandatory
2. You will need following documents to complete the process
   • Photo
   • Signature (.jpeg, .png format)
3. Details of two witnesses required:
   • Name
   • Designation
   • Signature (.jpeg, .png format)
4. Both documents must be filled at one time`,
  next: 'Next',
  something_went_wrong_: 'Something went wrong',
  indemnity_bond_form_title: 'Indemnity Bond Form',
  relation: 'Relation',
  relation_name: 'Relation Name',
  residence: 'Residence',
  employment_at: 'Employment At',
  duration: 'Duration',
  date: 'Date',
  month: 'Month',
  year: 'Year',
  campus: 'Campus',
  district: 'District',
  witness_name: 'Witness Name',
  signature_of_witness_bipard: 'Signature of Witness (BIPARD)',
  err_signature_of_witness_bipard: 'Signature of Witness (BIPARD) is required',
  preview: 'Preview',
  witness_designation_required: 'Witness designation is required',
  witness_name_required: 'Witness name is required',
  district_required: 'District is required',
  campus_required: 'Campus is required',
  relation_name_required: 'Relation Name is required',
  relation_required: 'Relation is required',
  empployme: 'Employme.',
  indemnity_bond_preview: 'Indemnity Bond Preview',
  indemnity_heading: 'GOOD BEHAVIOUR / INDEMNITY BOND BY TRAINEES',
  hindi_institute_title: 'बिहार लोक प्रशासन एवं ग्रामीण विकास संस्थान',
  hindi_address: 'कुशीधारा, गया - 823001',
  institute_full_name:
    'Bihar Institute of Public Administration & Rural Development',
  institute_address: 'Kushidhara, Gaya Jee - 823001',
  indemnifier_details: 'Indemnifier Details',
  witness_details_bipard: 'Witness Details (BIPARD)',
  name_of_indemnifier: 'Name of Indemnifier:',
  signature_of_indemnifier: '(Signature of Indemnifier)',
  signature_label: '(Signature)',
  no_file_uploaded: 'No File Uploaded',
  residence_of: 'Residence Of',
  employed_as_posted_at: 'employed as posted at',
  indemnity_clauses: [
    `I am aware of all the Government of India and State Acts/Laws/Regulations of the statutory bodies with respect to the Arms, Alcohols, Narcotics and Psychotropic Substances and other laws attracted in the event of any criminal offence committed by me during this training program. I shall not consume any tobacco, cigarette or other such substances during the training.`,
    `I will follow, abide and comply with all the directions given by officials, the course coordinator and the management of BIPARD.`,
    `In the event of residential training, I will not step outside the campus, in whatsoever situation, without having obtained due permission in written by the BIPARD. Nor will I keep/meet any person in my room.`,
    `I will keep my mobile phone/pager in silent mode. I shall not use mobile phone/pager during the training sessions and in the event of contravention of the same, the same shall be confiscated by the BIPARD for the remaining period of the training.`,
    `I will not cause any destruction or damage to any property of BIPARD intentionally or unintentionally and in case of such damage, I would be liable to be realized penalty against the same by the BIPARD.`,
    `At the time of breakfast, lunch, high tea and dinner, I shall remain present in the cafeteria/mess on the fixed time and I shall not waste food and in case of wastage of food, I shall be liable to be realized penalty against the same by the BIPARD.`,
    `I shall keep the premises of BIPARD clean, shall throw garbage only in dustbin and shall not litter anywhere and in the event of contravention of the same, I shall be liable to be realized penalty by the BIPARD.`,
    `I shall not step outside the classroom or roam around during the training sessions. During the tea break between the training sessions, I shall maintain silence and decorum of the classroom.`,
    `I will fully abide by the attendance rules and if I do not attend any training session without having obtained due permission by the BIPARD, I shall be liable to be punished as per due provisions.`,
    `In the event of residential training, while leaving the room, I shall switch off the lights, fans, AC etc. and in the event of contravention of the same, I shall be liable to be penalized by the BIPARD.`,
    `I shall follow the dress code as prescribed by BIPARD during the training and shall always carry my identity card issued by BIPARD.`,
    `During my stay in the hostel/campus, I shall not play loud music or any electronic device and maintain silence in the hostel.`,
    `I shall not engage myself in any tussle or fracas with any fellow trainee or staff at BIPARD.`,
    `I shall respect and regard all officials, faculties and resource persons of the BIPARD and shall not engage myself in any fracas with them.`,
    `I shall respect and regard other trainees, will not encroach upon their privacy and will maintain harmony and cordial relations with them.`,
    `I shall follow, abide and comply by all the rules, regulations and guidelines with regard to the training, hostel, discipline, training camps, trekking, yoga, meditation and exercises and other activities either conducted in physical or virtual mode as may be notified by BIPARD from time to time.`,
    `I have taken the required immunization, including for COVID-19 and I am not suffering from any communicable disease or any serious health illness, including mental illness. In case I am suffering from any illness, I would inform the course coordinator with regard to the same with complete details before the commencement of the training session and the decision of BIPARD in that regard shall be acceptable to me.`,
    `I will attend and participate in all the training sessions, physical exercises, outdoor excursions, yoga activities, sporting activities, cultural activities and such other activities within or outside the campus (including within or outside Bihar) at the fixed dates and time. I shall be willing to travel through such mode as decided by the BIPARD. I understand that the training program is rigorous and includes physical/mental exertion and therefore fully aware of the risks involved. I shall not hold BIPARD wholly or partly responsible in case of any accident, illness, injury or death.`,
    `I shall maintain the discipline, decorum, peace and tranquility at the premises of BIPARD and any loss and/or damages caused due to any undesirable action on my part would attract criminal prosecution/admissible claims/punishment/penalty as per the existing laws and procedures.`,
    `I also understand that, in case I break any of the above conditions, the BIPARD fully reserves the right to foreclose my training and send me back, apart from initiative such Departmental action as it may be deem fit.`,
    `I have no history of any serious physical or mental illness that would render me unfit for BIPARD training including physical training, Exposure visit etc. I have provided all information without withholding anything.`,
  ],
  indemnity_participation_prefix: 'hereby affirm that I am participating in',
  indemnity_program_commencing:
    'days/months training program voluntarily which is commencing from',
  indemnity_day_label: 'day',
  indemnity_month_label: 'month',
  indemnity_year_label: 'year',
  indemnity_scheduled_at:
    "scheduled to be conducted at Bihar Institute of Public Administration and Rural Development (hereinafter referred to as 'BIPARD') at campus",
  indemnity_and_declare:
    ', Bihar and do hereby undertake and declare the following:',
  document_details: 'Document Details',
  signature: 'Signature',
  photo: 'Photo',
  aadhar_card: 'Aadhar Card',
  no_documnet_available: 'No document available',

  /* Edit Profile screen strings */
  edit_profile: 'Edit Profile',
  date_of_birth: 'Date of Birth',
  other_email: 'Other Email',
  emergency_mobile: 'Emergency Mobile Number',
  pay_scale: 'Pay Scale',
  basic_pay_scale: 'Basic Pay Scale',
  office_district: 'Office District',
  office_pin_code: 'Office PIN Code',
  residential_district: 'Residential District',
  residential_pin_code: 'Residential PIN Code',
  doj_department: 'DOJ(Department)',
  doj_bipard: 'DOJ(BIPARD)',
  date_of_retirement: 'Date of Retirement(Job)',
  work_experience_details: 'Work Experience Details',
  computing_course_label:
    'Have you attended / completed any course on computing?',
  enter_details: 'Enter Details',
  knowledge_of_computing_label: 'Knowledge of computing, if any:',
  other_training_label:
    'Have you attended / completed any other training section?',
  upload_photo: 'Upload Photo',
  upload_signature: 'Upload Signature',
  upload_aadhar_card: 'Upload Aadhar Card',
  aadhar_merge_note: '* Note - Please merge aadhar front & back in one file',

  /* Validation / messages used in Edit Profile */
  details_is_required: 'Details is required',
  aadhar_card_required: 'Aadhar card is required',
  sign_required: 'Sign is required',
  photo_required: 'Photo is required',
  work_experience_details_required: 'Work Experience Details is required',
  date_of_retirement_required: 'Date of Retirement(Job) is required',
  doj_bipard_required: 'DOJ(BIPARD) is required',
  doj_department_required: 'DOJ(Department) is required',
  residential_pin_required: 'Residential PIN Code is required',
  enter_valid_residential_pin: 'Enter valid Residential PIN Code',
  residential_district_required: 'Residential District is required',
  residential_address_required: 'Residential Address is required',
  office_pin_required: 'Office PIN Code is required',
  enter_valid_office_pin: 'Enter valid Office pin code',
  office_district_required: 'Office District is required',
  office_address_required: 'Office Address is required',
  category_required: 'Category is required',
  basic_pay_required: 'Basic Pay Scale is required',
  pay_scale_required: 'Pay Scale is required',
  emergency_mobile_required: 'Emergency Mobile Number is required',
  enter_valid_emergency_mobile: 'Enter valid Emergency mobile number',
  qualification_required: 'Educatonal Qualification is required',
  mobile_required: 'Mobile Number is required',
  enter_valid_mobile: 'Enter valid mobile number',
  designation_required: 'Designation is required',
  office_email_required: 'Office email is required',
  enter_valid_email: 'Enter a Valid Email',
  dob_required: 'Date of Birth is required',
  gender_required: 'Gender is required',
  marital_status_required: 'Marital Status is required',
  pan_required: 'PAN is required',
  pan_invalid: 'Enter a Valid PAN Card Number',
  mother_name_required: 'Mother Name is required',
  father_name_required: 'Father Name is required',
  aadhar_required: 'Aadhar is required',
  aadhar_invalid: 'Enter The Correct Aadhaar Number',
};
